-- Tabela ITEM
CREATE TABLE ITEM 
(
    ID_ITEM              INTEGER NOT NULL,
    NM_ITEM              VARCHAR2(50) NOT NULL,
    DS_ITEM              VARCHAR2(100),
    NR_NIVEL_MIN_ESTOQUE INTEGER NOT NULL
);

COMMENT ON TABLE ITEM IS 'Tabela que armazena os itens do estoque';
COMMENT ON COLUMN ITEM.ID_ITEM IS 'Identificador único do item';
COMMENT ON COLUMN ITEM.NM_ITEM IS 'Nome do item';
COMMENT ON COLUMN ITEM.DS_ITEM IS 'Descrição do item';
COMMENT ON COLUMN ITEM.NR_NIVEL_MIN_ESTOQUE IS 'Quantidade mínima de estoque do item';

ALTER TABLE ITEM
ADD CONSTRAINT ITEM_PK PRIMARY KEY (ID_ITEM);

-- Tabela LOTE
CREATE TABLE LOTE
(
    ID_LOTE       INTEGER NOT NULL,
    NR_LOTE       VARCHAR2(20) NOT NULL,
    DT_VALIDADE   DATE NOT NULL,
    NR_QUANTIDADE INTEGER NOT NULL,
    ID_ITEM       INTEGER NOT NULL
);

COMMENT ON TABLE LOTE IS 'Tabela que armazena os lotes de cada item';
COMMENT ON COLUMN LOTE.ID_LOTE IS 'Identificador único do lote';
COMMENT ON COLUMN LOTE.NR_LOTE IS 'Número do lote';
COMMENT ON COLUMN LOTE.DT_VALIDADE IS 'Data de validade do lote';
COMMENT ON COLUMN LOTE.NR_QUANTIDADE IS 'Quantidade disponível no lote';
COMMENT ON COLUMN LOTE.ID_ITEM IS 'Referência ao item deste lote';

ALTER TABLE LOTE
ADD CONSTRAINT LOTE_PK PRIMARY KEY (ID_LOTE);

-- Tabela USUARIO
CREATE TABLE USUARIO
(
    ID_USUARIO    INTEGER NOT NULL,
    NM_USUARIO    VARCHAR2(50),
    DS_LOGIN      VARCHAR2(40) NOT NULL,
    DS_SENHA_HASH VARCHAR2(60) NOT NULL,
    TP_USUARIO    VARCHAR2(10) NOT NULL
);

COMMENT ON TABLE USUARIO IS 'Tabela que armazena os usuários do sistema';
COMMENT ON COLUMN USUARIO.ID_USUARIO IS 'Identificador único do usuário';
COMMENT ON COLUMN USUARIO.NM_USUARIO IS 'Nome completo do usuário';
COMMENT ON COLUMN USUARIO.DS_LOGIN IS 'Login do usuário';
COMMENT ON COLUMN USUARIO.DS_SENHA_HASH IS 'Senha do usuário (hash)';
COMMENT ON COLUMN USUARIO.TP_USUARIO IS 'Tipo do usuário (ADMIN, OPERADOR, VISUALIZADOR)';

ALTER TABLE USUARIO
ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO);

-- Tabela TIPO_MOVIMENTACAO
CREATE TABLE TIPO_MOVIMENTACAO
(
    ID_TP_MOVIMENTACAO   INTEGER NOT NULL,
    DS_TIPO_MOVIMENTACAO VARCHAR2(50)
);

COMMENT ON TABLE TIPO_MOVIMENTACAO IS 'Tabela que armazena os tipos de movimentação';
COMMENT ON COLUMN TIPO_MOVIMENTACAO.ID_TP_MOVIMENTACAO IS 'Identificador único do tipo de movimentação';
COMMENT ON COLUMN TIPO_MOVIMENTACAO.DS_TIPO_MOVIMENTACAO IS 'Descrição do tipo de movimentação (ENTRADA, SAIDA, AJUSTE)';

ALTER TABLE TIPO_MOVIMENTACAO
ADD CONSTRAINT TIPO_MOVIMENTACAO_PK PRIMARY KEY (ID_TP_MOVIMENTACAO);

-- Tabela MOVIMENTACAO
CREATE TABLE MOVIMENTACAO
(
    ID_MOVIMENTACAO    INTEGER NOT NULL,
    DT_HR_MOVIMENTACAO TIMESTAMP WITH TIME ZONE NOT NULL,
    NR_QUANTIDADE_MOV  INTEGER NOT NULL,
    ID_LOTE            INTEGER NOT NULL,
    ID_USUARIO         INTEGER NOT NULL,
    ID_TP_MOVIMENTACAO INTEGER NOT NULL
);

COMMENT ON TABLE MOVIMENTACAO IS 'Tabela que registra todas as movimentações de estoque';
COMMENT ON COLUMN MOVIMENTACAO.ID_MOVIMENTACAO IS 'Identificador único da movimentação';
COMMENT ON COLUMN MOVIMENTACAO.DT_HR_MOVIMENTACAO IS 'Data e hora da movimentação';
COMMENT ON COLUMN MOVIMENTACAO.NR_QUANTIDADE_MOV IS 'Quantidade movimentada';
COMMENT ON COLUMN MOVIMENTACAO.ID_LOTE IS 'Referência ao lote movimentado';
COMMENT ON COLUMN MOVIMENTACAO.ID_USUARIO IS 'Referência ao usuário que realizou a movimentação';
COMMENT ON COLUMN MOVIMENTACAO.ID_TP_MOVIMENTACAO IS 'Referência ao tipo da movimentação';

ALTER TABLE MOVIMENTACAO
ADD CONSTRAINT MOVIMENTACAO_PK PRIMARY KEY (ID_MOVIMENTACAO);

-- =====================
-- Constraints de FK
-- =====================
ALTER TABLE LOTE
ADD CONSTRAINT FK_ITEM_LOTE FOREIGN KEY (ID_ITEM)
REFERENCES ITEM (ID_ITEM);

ALTER TABLE MOVIMENTACAO
ADD CONSTRAINT FK_MOV_LOTE FOREIGN KEY (ID_LOTE)
REFERENCES LOTE (ID_LOTE);

ALTER TABLE MOVIMENTACAO
ADD CONSTRAINT FK_MOV_TIPO_MOVIMENTACAO FOREIGN KEY (ID_TP_MOVIMENTACAO)
REFERENCES TIPO_MOVIMENTACAO (ID_TP_MOVIMENTACAO);

ALTER TABLE MOVIMENTACAO
ADD CONSTRAINT FK_MOV_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO);

-- =====================
-- Sequences
-- =====================
CREATE SEQUENCE seq_item START WITH 1 MINVALUE 1 NOCACHE ORDER;
CREATE SEQUENCE seq_lote START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE seq_mov START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE seq_usuario START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE seq_tipo_movimentacao START WITH 1 NOCACHE;